# Generated by Django 5.0.4 on 2024-04-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cliente_clave_alter_cliente_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estatus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
