# Generated by Django 5.0.4 on 2024-05-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_pedido_estatus_alter_pedido_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entregado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
