# Generated by Django 5.0.4 on 2024-05-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_pedido_fecha_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
