# Generated by Django 5.0.4 on 2024-05-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_pedido_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
