# Generated by Django 5.0.4 on 2024-06-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_pedido_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='anticipo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='costo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
