# Generated by Django 5.0.4 on 2024-06-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_pedido_anticipo_alter_pedido_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='celular',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
