# Generated by Django 5.0.4 on 2024-09-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_pedido_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagenUrl',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
