# Generated by Django 5.0.4 on 2025-01-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_pedido_imagenurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagenUrlExternal',
            field=models.TextField(default=''),
        ),
    ]
