# Generated by Django 5.0.4 on 2025-03-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_pedido_imagenurlexternal'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['id'], name='agenda_pedi_id_dce312_idx'),
        ),
    ]
