# Generated by Django 5.0.4 on 2025-03-15 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_pedido_agenda_pedi_id_dce312_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='imagen',
        ),
    ]
